//
// DO NOT EDIT - File generated by the org.cthing.build-constants Gradle plugin.
//

package org.cthing.test;

@SuppressWarnings("all")
final class Constants {

    static final String PROJECT_NAME = "testProject";
    static final String PROJECT_VERSION = "1.2.3";
    static final String PROJECT_GROUP = "org.cthing";
    static final long BUILD_TIME = 1718946725000L;
    static final String BUILD_DATE = "2024-06-21T05:12:05Z";

    private Constants() { }
}
