//
// DO NOT EDIT - File generated by the org.cthing.build-constants Gradle plugin.
//

package org.cthing.test;

@SuppressWarnings("all")
public final class Constants {

    public static final String PROJECT_NAME = "testProject";
    public static final String PROJECT_VERSION = "1.2.3";
    public static final String PROJECT_GROUP = "org.cthing";
    public static final long BUILD_TIME = 1718946725000L;
    public static final String BUILD_DATE = "2024-06-21T05:12:05Z";
    public static final String ABC = "def";
    public static final String CUSTOM1 = "Hello";
    public static final String CUSTOM2 = "World";
    public static final boolean CUSTOM3 = true;
    public static final long tuv = 2300L;
    public static final int xyz = 17;

    private Constants() { }
}
