//
// DO NOT EDIT - File generated by the org.cthing.build-constants Gradle plugin.
//

package org.cthing.test;

@SuppressWarnings("all")
public final class Constants {

    public static final String PROJECT_NAME = "testProject";
    public static final String PROJECT_VERSION = "1.2.3";
    public static final String PROJECT_GROUP = "org.cthing";
    public static final long BUILD_TIME = 1718946725000L;
    public static final String BUILD_DATE = "2024-06-21T05:12:05Z";

    private Constants() { }
}
